name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  ubuntu20-blas:
    name: ubuntu 20.04
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt-get install gfortran libopenmpi-dev openmpi-common openmpi-bin
      - name: info
        run: |
          g++ -v
          mpic++ -v
          cmake --version
      - name: build
        run: |
          echo 'DEAL_II_CONFOPTS="-D CMAKE_BUILD_TYPE=Debug -D DEAL_II_LINKER_FLAGS=-fuse-ld=bfd"' >> candi.cfg
          # use our cmake version, as the runner has 3.19 installed, which is too new for deal.II
          ./candi.sh -j 2 --packages="once:cmake once:openblas once:p4est dealii"
          cd ~/dealii-candi/tmp/build/deal.II-* && cat detailed.log

  ubuntu22:
    name: ubuntu 22.04
    runs-on: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          sudo apt-get install gfortran libopenmpi-dev openmpi-common openmpi-bin cmake
      - name: info
        run: |
          g++ -v
          mpic++ -v
          cmake --version
      - name: build
        run: |
          ./candi.sh -j 2 --packages="once:openblas once:p4est dealii"
          cd ~/dealii-candi/tmp/build/deal.II-* && cat detailed.log

  osx-minimal:
    name: OSX clang
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          # force cmake version:
          pip install cmake==3.20.5
          echo "/Library/Frameworks/Python.framework/Versions/2.7/bin" >> $GITHUB_PATH
          brew install openmpi
          brew reinstall gcc@11
      - name: info
        run: |
          mpicxx -v
          cmake --version
      - name: build
        run: |
          echo 'DEAL_II_CONFOPTS="-D CMAKE_BUILD_TYPE=Debug"' >> candi.cfg
          ./candi.sh -j 2 --packages="boost dealii"
          cd ~/dealii-candi/tmp/build/deal.II-* && cat detailed.log

  macos-gcc:
    name: macos-gcc
    runs-on: [macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          brew install openmpi gcc@11

      - name: info
        run: |
          # Export the compilers
          export OMPI_CXX=g++-11; export OMPI_CC=gcc-11; export OMPI_FC=gfortran-11

          # Show compilers and cmake versions
          mpicc --version
          mpicxx --version
          mpif90 --version
          mpif77 --version
          cmake --version
          python --version
          python3 --version

      - name: build
        run: |
          # Export the compilers
          export OMPI_CXX=g++-11; export OMPI_CC=gcc-11; export OMPI_FC=gfortran-11

          # Compile dealii in DEBUG mode only
          echo 'DEAL_II_CONFOPTS="-D CMAKE_BUILD_TYPE=Debug"' >> candi.cfg

          ./candi.sh -j 2 --packages="once:p4est once:petsc dealii"
          cd ~/dealii-candi/tmp/build/deal.II-* && cat detailed.log && ctest --output-on-failure -j 2
